// <auto-generated />
using System;
using D4HSE.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace D4HSE.Infrastructure.Migrations
{
    [DbContext(typeof(HseCockpitDbContext))]
    [Migration("20260719045308_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("D4HSE.Core.Entities.Asset", b =>
                {
                    b.Property<Guid>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("asset_name");

                    b.Property<string>("AssetType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("asset_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("AssetId")
                        .HasName("pk_assets");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_assets_site_id");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("D4HSE.Core.Entities.BarrierHealthObservation", b =>
                {
                    b.Property<Guid>("ObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("observation_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BarrierId")
                        .HasColumnType("uuid")
                        .HasColumnName("barrier_id");

                    b.Property<decimal?>("ConditionScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("condition_score");

                    b.Property<string>("DataQualityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("VALID")
                        .HasColumnName("data_quality_status");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("ObservedAt")
                        .HasColumnType("date")
                        .HasColumnName("observed_at");

                    b.Property<string>("RagStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("rag_status");

                    b.Property<string>("SourceCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_category");

                    b.HasKey("ObservationId")
                        .HasName("pk_barrier_health_observations");

                    b.HasIndex("BarrierId", "ObservedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_barrier_health_observations_barrier_id_observed_at");

                    b.ToTable("barrier_health_observations", null, t =>
                        {
                            t.HasCheckConstraint("ck_barrier_health_observations_data_quality_status", "data_quality_status IN ('VALID','FLAGGED','CONFLICT')");

                            t.HasCheckConstraint("ck_barrier_health_observations_rag_status", "rag_status IN ('GREEN','AMBER','RED')");
                        });
                });

            modelBuilder.Entity("D4HSE.Core.Entities.ComplianceStatus", b =>
                {
                    b.Property<Guid>("ComplianceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("compliance_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("AssessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assessed_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("ComplianceId")
                        .HasName("pk_compliance_statuses");

                    b.HasIndex("SiteId", "PeriodEnd")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_compliance_statuses_site_id_period_end");

                    b.ToTable("compliance_statuses", null, t =>
                        {
                            t.HasCheckConstraint("ck_compliance_status_status", "status IN ('COMPLIANT','NON_COMPLIANT','UNKNOWN')");
                        });
                });

            modelBuilder.Entity("D4HSE.Core.Entities.CriticalBarrier", b =>
                {
                    b.Property<Guid>("BarrierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("barrier_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("BarrierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("barrier_name");

                    b.Property<string>("BarrierType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("barrier_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CriticalityRank")
                        .HasColumnType("integer")
                        .HasColumnName("criticality_rank");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("BarrierId")
                        .HasName("pk_critical_barriers");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_critical_barriers_asset_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_critical_barriers_site_id");

                    b.ToTable("critical_barriers", (string)null);
                });

            modelBuilder.Entity("D4HSE.Core.Entities.Incident", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("DataQualityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("VALID")
                        .HasColumnName("data_quality_status");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("IncidentDate")
                        .HasColumnType("date")
                        .HasColumnName("incident_date");

                    b.Property<string>("IncidentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("incident_type");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SourceCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_category");

                    b.HasKey("IncidentId")
                        .HasName("pk_incidents");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_incidents_asset_id");

                    b.HasIndex("SiteId", "IncidentDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_incidents_site_id_incident_date");

                    b.ToTable("incidents", null, t =>
                        {
                            t.HasCheckConstraint("ck_incidents_data_quality_status", "data_quality_status IN ('VALID','FLAGGED')");

                            t.HasCheckConstraint("ck_incidents_severity", "severity IN ('LOW','MEDIUM','HIGH','CRITICAL')");
                        });
                });

            modelBuilder.Entity("D4HSE.Core.Entities.MaintenanceRecord", b =>
                {
                    b.Property<Guid>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("maintenance_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActivityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("activity_type");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("DataQualityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("VALID")
                        .HasColumnName("data_quality_status");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("MaintenanceDate")
                        .HasColumnType("date")
                        .HasColumnName("maintenance_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Outcome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SourceCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_category");

                    b.HasKey("MaintenanceId")
                        .HasName("pk_maintenance_records");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_maintenance_records_site_id");

                    b.HasIndex("AssetId", "MaintenanceDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_maintenance_records_asset_id_maintenance_date");

                    b.ToTable("maintenance_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_maintenance_records_data_quality_status", "data_quality_status IN ('VALID','FLAGGED')");
                        });
                });

            modelBuilder.Entity("D4HSE.Core.Entities.NearMiss", b =>
                {
                    b.Property<Guid>("NearMissId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("near_miss_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("DataQualityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("VALID")
                        .HasColumnName("data_quality_status");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("PotentialSeverity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("potential_severity");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SourceCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_category");

                    b.HasKey("NearMissId")
                        .HasName("pk_near_misses");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_near_misses_asset_id");

                    b.HasIndex("SiteId", "EventDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_near_misses_site_id_event_date");

                    b.ToTable("near_misses", null, t =>
                        {
                            t.HasCheckConstraint("ck_near_misses_data_quality_status", "data_quality_status IN ('VALID','FLAGGED')");

                            t.HasCheckConstraint("ck_near_misses_potential_severity", "potential_severity IN ('LOW','MEDIUM','HIGH','CRITICAL')");
                        });
                });

            modelBuilder.Entity("D4HSE.Core.Entities.RiskItem", b =>
                {
                    b.Property<Guid>("RiskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("risk_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid?>("BarrierId")
                        .HasColumnType("uuid")
                        .HasColumnName("barrier_id");

                    b.Property<DateOnly?>("IdentifiedAt")
                        .HasColumnType("date")
                        .HasColumnName("identified_at");

                    b.Property<DateOnly?>("ResolvedAt")
                        .HasColumnType("date")
                        .HasColumnName("resolved_at");

                    b.Property<string>("RiskDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risk_description");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("OPEN")
                        .HasColumnName("status");

                    b.HasKey("RiskId")
                        .HasName("pk_risk_items");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_risk_items_asset_id");

                    b.HasIndex("BarrierId")
                        .HasDatabaseName("ix_risk_items_barrier_id");

                    b.HasIndex("SiteId", "Status")
                        .HasDatabaseName("ix_risk_items_site_id_status");

                    b.ToTable("risk_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_risk_items_severity", "severity IN ('LOW','MEDIUM','HIGH','CRITICAL')");

                            t.HasCheckConstraint("ck_risk_items_status", "status IN ('OPEN','CLOSED','MONITORING')");
                        });
                });

            modelBuilder.Entity("D4HSE.Core.Entities.Site", b =>
                {
                    b.Property<Guid>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("site_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("site_name");

                    b.HasKey("SiteId")
                        .HasName("pk_sites");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("D4HSE.Core.Entities.Asset", b =>
                {
                    b.HasOne("D4HSE.Core.Entities.Site", "Site")
                        .WithMany("Assets")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assets_sites_site_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("D4HSE.Core.Entities.BarrierHealthObservation", b =>
                {
                    b.HasOne("D4HSE.Core.Entities.CriticalBarrier", "CriticalBarrier")
                        .WithMany("HealthObservations")
                        .HasForeignKey("BarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_barrier_health_observations_critical_barriers_barrier_id");

                    b.Navigation("CriticalBarrier");
                });

            modelBuilder.Entity("D4HSE.Core.Entities.ComplianceStatus", b =>
                {
                    b.HasOne("D4HSE.Core.Entities.Site", "Site")
                        .WithMany("ComplianceStatuses")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_compliance_statuses_sites_site_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("D4HSE.Core.Entities.CriticalBarrier", b =>
                {
                    b.HasOne("D4HSE.Core.Entities.Asset", "Asset")
                        .WithMany("CriticalBarriers")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_critical_barriers_assets_asset_id");

                    b.HasOne("D4HSE.Core.Entities.Site", "Site")
                        .WithMany("CriticalBarriers")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_critical_barriers_sites_site_id");

                    b.Navigation("Asset");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("D4HSE.Core.Entities.Incident", b =>
                {
                    b.HasOne("D4HSE.Core.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .HasConstraintName("fk_incidents_assets_asset_id");

                    b.HasOne("D4HSE.Core.Entities.Site", "Site")
                        .WithMany("Incidents")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incidents_sites_site_id");

                    b.Navigation("Asset");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("D4HSE.Core.Entities.MaintenanceRecord", b =>
                {
                    b.HasOne("D4HSE.Core.Entities.Asset", "Asset")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_records_assets_asset_id");

                    b.HasOne("D4HSE.Core.Entities.Site", "Site")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_records_sites_site_id");

                    b.Navigation("Asset");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("D4HSE.Core.Entities.NearMiss", b =>
                {
                    b.HasOne("D4HSE.Core.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .HasConstraintName("fk_near_misses_assets_asset_id");

                    b.HasOne("D4HSE.Core.Entities.Site", "Site")
                        .WithMany("NearMisses")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_near_misses_sites_site_id");

                    b.Navigation("Asset");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("D4HSE.Core.Entities.RiskItem", b =>
                {
                    b.HasOne("D4HSE.Core.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .HasConstraintName("fk_risk_items_assets_asset_id");

                    b.HasOne("D4HSE.Core.Entities.CriticalBarrier", "CriticalBarrier")
                        .WithMany("RiskItems")
                        .HasForeignKey("BarrierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_risk_items_critical_barriers_barrier_id");

                    b.HasOne("D4HSE.Core.Entities.Site", "Site")
                        .WithMany("RiskItems")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_risk_items_sites_site_id");

                    b.Navigation("Asset");

                    b.Navigation("CriticalBarrier");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("D4HSE.Core.Entities.Asset", b =>
                {
                    b.Navigation("CriticalBarriers");

                    b.Navigation("MaintenanceRecords");
                });

            modelBuilder.Entity("D4HSE.Core.Entities.CriticalBarrier", b =>
                {
                    b.Navigation("HealthObservations");

                    b.Navigation("RiskItems");
                });

            modelBuilder.Entity("D4HSE.Core.Entities.Site", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("ComplianceStatuses");

                    b.Navigation("CriticalBarriers");

                    b.Navigation("Incidents");

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("NearMisses");

                    b.Navigation("RiskItems");
                });
#pragma warning restore 612, 618
        }
    }
}
