namespace D4HSE.Core.Interfaces;

/// <summary>
/// The result of an AI Copilot query, containing the LLM answer grounded in HSE data,
/// source citations, matched recommendation rules, and data scope indicator.
/// </summary>
public class CopilotQueryResult
{
    /// <summary>
    /// The natural language answer generated by the LLM, grounded in retrieved HSE records.
    /// </summary>
    public string Answer { get; set; } = string.Empty;

    /// <summary>
    /// Citations to the source HSE records that support the answer.
    /// </summary>
    public IReadOnlyList<SourceCitation> Citations { get; set; } = [];

    /// <summary>
    /// Predefined recommended actions matched against the retrieved context.
    /// These are rule-based, never AI-generated.
    /// </summary>
    public IReadOnlyList<RecommendedAction> RecommendedActions { get; set; } = [];

    /// <summary>
    /// Indicates the data scope of the response:
    /// "full" — all requested data is available and high quality;
    /// "partial" — some retrieved records have quality flags;
    /// "out_of_scope" — the query references data outside MVP categories.
    /// </summary>
    public string DataScope { get; set; } = "full";
}
