using Amazon.CDK;
using Amazon.CDK.AWS.DynamoDB;
using Amazon.CDK.AWS.EC2;
using Amazon.CDK.AWS.KMS;
using Amazon.CDK.AWS.RDS;
using Amazon.CDK.AWS.SecretsManager;
using Amazon.CDK.AWS.SSM;
using Constructs;

namespace HSECockpit.Infra.Stacks;

/// <summary>
/// Properties required by DatabaseStack from other stacks.
/// </summary>
public class DatabaseStackProps : StackProps
{
    /// <summary>The VPC where the RDS instance will be deployed.</summary>
    public required IVpc Vpc { get; init; }

    /// <summary>The security group for the RDS instance (allows access from ECS and Lambda).</summary>
    public required ISecurityGroup RdsSecurityGroup { get; init; }

    /// <summary>The environment name (dev, staging, prod) to control removal policies.</summary>
    public required string EnvironmentName { get; init; }
}

/// <summary>
/// Data layer: RDS PostgreSQL (Multi-AZ) and DynamoDB table (DataQualityLog with TTL).
/// </summary>
public class DatabaseStack : Stack
{
    /// <summary>The RDS PostgreSQL database instance.</summary>
    public DatabaseInstance PostgresInstance { get; }

    /// <summary>The DynamoDB DataQualityLog table.</summary>
    public Table DataQualityLogTable { get; }

    /// <summary>The Secrets Manager secret containing Bedrock API configuration.</summary>
    public Secret BedrockConfigSecret { get; }

    public DatabaseStack(Construct scope, string id, DatabaseStackProps props) : base(scope, id, props)
    {
        var isProduction = props.EnvironmentName == "prod";

        // ─── KMS Key for RDS encryption at rest ───────────────────────────────────────
        var rdsEncryptionKey = new Key(this, "HSECockpit-RDS-KMS", new KeyProps
        {
            Alias = "alias/hsecockpit-rds",
            Description = "Customer-managed KMS key for HSECockpit RDS encryption at rest",
            EnableKeyRotation = true,
            RemovalPolicy = isProduction ? RemovalPolicy.RETAIN : RemovalPolicy.DESTROY
        });

        // ─── RDS PostgreSQL (Multi-AZ) ────────────────────────────────────────────────
        PostgresInstance = new DatabaseInstance(this, "HSECockpit-PostgreSQL", new DatabaseInstanceProps
        {
            Engine = DatabaseInstanceEngine.Postgres(new PostgresInstanceEngineProps
            {
                Version = PostgresEngineVersion.VER_16
            }),
            InstanceType = Amazon.CDK.AWS.EC2.InstanceType.Of(InstanceClass.BURSTABLE3, InstanceSize.MEDIUM),
            Vpc = props.Vpc,
            VpcSubnets = new SubnetSelection
            {
                SubnetType = SubnetType.PRIVATE_WITH_EGRESS
            },
            SecurityGroups = new[] { props.RdsSecurityGroup },
            MultiAz = true,
            AllocatedStorage = 50,
            MaxAllocatedStorage = 200,
            StorageType = StorageType.GP3,
            StorageEncrypted = true,
            StorageEncryptionKey = rdsEncryptionKey,
            DatabaseName = "hsecockpit",
            Credentials = Credentials.FromGeneratedSecret("hsecockpit_admin", new CredentialsBaseOptions
            {
                SecretName = "hsecockpit/rds/credentials"
            }),
            BackupRetention = Duration.Days(7),
            PreferredBackupWindow = "02:00-03:00",
            PreferredMaintenanceWindow = "sun:04:00-sun:05:00",
            DeletionProtection = isProduction,
            RemovalPolicy = isProduction ? RemovalPolicy.RETAIN : RemovalPolicy.DESTROY,
            PubliclyAccessible = false,
            AutoMinorVersionUpgrade = true
        });

        // ─── DynamoDB Table: DataQualityLog ───────────────────────────────────────────
        DataQualityLogTable = new Table(this, "HSECockpit-DataQualityLog", new TableProps
        {
            TableName = "DataQualityLog",
            PartitionKey = new Amazon.CDK.AWS.DynamoDB.Attribute
            {
                Name = "pk",
                Type = AttributeType.STRING
            },
            SortKey = new Amazon.CDK.AWS.DynamoDB.Attribute
            {
                Name = "sk",
                Type = AttributeType.STRING
            },
            BillingMode = BillingMode.PAY_PER_REQUEST,
            TimeToLiveAttribute = "ttl",
            Encryption = TableEncryption.AWS_MANAGED,
            RemovalPolicy = isProduction ? RemovalPolicy.RETAIN : RemovalPolicy.DESTROY,
            PointInTimeRecovery = true
        });

        // ─── Secrets Manager: Bedrock API Configuration (placeholder) ────────────────
        // Note: RDS connection string secret is auto-generated by the RDS construct
        // at path "hsecockpit/rds/credentials" (see Credentials.FromGeneratedSecret above).
        BedrockConfigSecret = new Secret(this, "HSECockpit-Bedrock-Config", new SecretProps
        {
            SecretName = "hsecockpit/bedrock/config",
            Description = "Placeholder configuration for Amazon Bedrock API (Claude model)",
            GenerateSecretString = new SecretStringGenerator
            {
                SecretStringTemplate = System.Text.Json.JsonSerializer.Serialize(new
                {
                    modelId = "anthropic.claude-3-sonnet-20240229-v1:0",
                    region = "us-east-1",
                    maxTokens = 4096
                }),
                GenerateStringKey = "_placeholder"
            },
            RemovalPolicy = isProduction ? RemovalPolicy.RETAIN : RemovalPolicy.DESTROY
        });

        // ─── Systems Manager Parameter Store ─────────────────────────────────────────
        _ = new StringParameter(this, "HSECockpit-RAG-Thresholds", new StringParameterProps
        {
            ParameterName = "/hse/barriers/rag-thresholds",
            Description = "RAG status thresholds for critical barrier health (Green/Amber/Red)",
            StringValue = "{\"greenMin\": 80, \"amberMin\": 50, \"amberMax\": 79, \"redMax\": 49}"
        });

        _ = new StringParameter(this, "HSECockpit-Risk-Weights", new StringParameterProps
        {
            ParameterName = "/hse/risk/weights",
            Description = "Risk score formula weights for site risk calculation",
            StringValue = "{\"incidentSeverity\": 0.25, \"nearMissFrequency\": 0.25, \"openRiskCount\": 0.25, \"barrierHealth\": 0.25}"
        });

        _ = new StringParameter(this, "HSECockpit-Risk-Banding", new StringParameterProps
        {
            ParameterName = "/hse/risk/banding",
            Description = "Risk heatmap banding thresholds",
            StringValue = "{\"low\": 25, \"medium\": 50, \"high\": 75, \"critical\": 100}"
        });

        _ = new StringParameter(this, "HSECockpit-Ingestion-Schedule", new StringParameterProps
        {
            ParameterName = "/hse/ingestion/schedule",
            Description = "Data ingestion cron/rate expression",
            StringValue = "rate(6 hours)"
        });

        _ = new StringParameter(this, "HSECockpit-Ingestion-LastRun", new StringParameterProps
        {
            ParameterName = "/hse/ingestion/last-run",
            Description = "Timestamp of the last successful data ingestion run",
            StringValue = "1970-01-01T00:00:00Z"
        });

        _ = new StringParameter(this, "HSECockpit-DataQuality-FreshnessThreshold", new StringParameterProps
        {
            ParameterName = "/hse/data-quality/freshness-threshold-hours",
            Description = "Hours after which ingested data is considered stale",
            StringValue = "24"
        });

        // ─── CloudFormation Outputs ───────────────────────────────────────────────────
        _ = new CfnOutput(this, "PostgresEndpoint", new CfnOutputProps
        {
            Value = PostgresInstance.DbInstanceEndpointAddress,
            Description = "RDS PostgreSQL endpoint address",
            ExportName = "HSECockpit-RDS-Endpoint"
        });

        _ = new CfnOutput(this, "PostgresSecretArn", new CfnOutputProps
        {
            Value = PostgresInstance.Secret!.SecretArn,
            Description = "ARN of the Secrets Manager secret for RDS credentials",
            ExportName = "HSECockpit-RDS-SecretArn"
        });

        _ = new CfnOutput(this, "DataQualityLogTableName", new CfnOutputProps
        {
            Value = DataQualityLogTable.TableName,
            Description = "DynamoDB DataQualityLog table name",
            ExportName = "HSECockpit-DynamoDB-DataQualityLog"
        });

        _ = new CfnOutput(this, "DataQualityLogTableArn", new CfnOutputProps
        {
            Value = DataQualityLogTable.TableArn,
            Description = "DynamoDB DataQualityLog table ARN",
            ExportName = "HSECockpit-DynamoDB-DataQualityLog-Arn"
        });

        _ = new CfnOutput(this, "BedrockConfigSecretArn", new CfnOutputProps
        {
            Value = BedrockConfigSecret.SecretArn,
            Description = "ARN of the Secrets Manager secret for Bedrock API configuration",
            ExportName = "HSECockpit-Bedrock-ConfigSecretArn"
        });
    }
}
