namespace D4HSE.Api.Models;

/// <summary>
/// Response DTO for the AI Copilot query endpoint.
/// Contains the LLM answer, source citations, predefined recommended actions, and data scope indicator.
/// </summary>
public class CopilotQueryResponse
{
    /// <summary>
    /// The natural language answer generated by the AI Copilot, grounded in retrieved HSE records.
    /// </summary>
    public string Answer { get; set; } = string.Empty;

    /// <summary>
    /// Citations to source HSE records that support the answer.
    /// </summary>
    public IReadOnlyList<SourceCitationResponse> Citations { get; set; } = [];

    /// <summary>
    /// Predefined recommended actions matched against the query context.
    /// These are rule-based and clearly distinct from factual observations.
    /// </summary>
    public IReadOnlyList<RecommendedActionResponse> RecommendedActions { get; set; } = [];

    /// <summary>
    /// Indicates the data scope of the response:
    /// "full" — all requested data is available;
    /// "partial" — some records have quality flags;
    /// "out_of_scope" — the query references data outside MVP categories.
    /// </summary>
    public string DataScope { get; set; } = "full";
}

/// <summary>
/// A citation to a source HSE record used to ground the copilot response.
/// </summary>
public class SourceCitationResponse
{
    /// <summary>
    /// The unique identifier of the cited record.
    /// </summary>
    public string RecordId { get; set; } = string.Empty;

    /// <summary>
    /// The type of record (e.g., "barrier_observation", "incident", "near_miss", "maintenance").
    /// </summary>
    public string RecordType { get; set; } = string.Empty;

    /// <summary>
    /// The site associated with the cited record.
    /// </summary>
    public Guid SiteId { get; set; }

    /// <summary>
    /// The asset associated with the cited record, if applicable.
    /// </summary>
    public Guid? AssetId { get; set; }

    /// <summary>
    /// Summary text content of the cited record.
    /// </summary>
    public string TextContent { get; set; } = string.Empty;

    /// <summary>
    /// Relevance score (0.0–1.0) from semantic search.
    /// </summary>
    public float RelevanceScore { get; set; }
}

/// <summary>
/// A predefined recommended action returned by the copilot.
/// </summary>
public class RecommendedActionResponse
{
    /// <summary>
    /// Unique identifier of the recommendation rule.
    /// </summary>
    public string RuleId { get; set; } = string.Empty;

    /// <summary>
    /// Human-readable label for the recommendation category.
    /// </summary>
    public string Label { get; set; } = string.Empty;

    /// <summary>
    /// The recommended action text.
    /// </summary>
    public string Action { get; set; } = string.Empty;

    /// <summary>
    /// Description of the condition that triggered this recommendation.
    /// </summary>
    public string TriggeringCondition { get; set; } = string.Empty;
}
